dist: trusty
env:
  matrix:
  - MOZ_HEADLESS=1
  global:
  - secure: Q/561bfts5JU2n5El+EH9Rsk3djTZvrMJIW+fsPJ8JJaDM8g0rZzx+cBVHyjlftzW19FncgZ91BbWLnSIoT7LYZYAnqlzCOm51NmtXrFFdj8tO0tMyr49FSaexF7kuopR/LY+NYuSKXglMkdzl8xP72+WKu5Ylzewj2h5rYTrQRAKZ+Qq8ZoC7+gooMHTY0h/m4n6OEcx/XCiTenXg9zAL3LgcJLRhmABGhNfCRwuHaOm8mngZ2PtZXLZ3nTwwOVoeiS56WTfMBto3Mc402zaJudF+2haJKJtt26ECNh7tNWS6T+ccxpH0TakZgC88aCgGwVvtOuh0hE1b0sRkkj1VHctiOjYApAj06S0e8Pwk158oMiZmNniG+ehKs7OYRb+Xcr/2OpLSsmpBsQimP84FAwsg4kZKET7yE3fBfygT/8vkez7X9Jg0qfggF2UtdrO+hhk8tpW7cU9LCvWX4Ms5P5Ou2e16cO2sqQI1zfcTzjmpvolxuEg/YLIAPG6pLQilHikWEzOcV8PgFMoWlBY7GVeAheCFS5Tek8uI4pMDHqw5cMFvnHTU4mtWNDBxa76Fof/K6QrCd7wqAuCebxUFc+SiF9z1xFXO0vn5IAKU8hwWuz1mM0ctKaZO1UcaYHnP+hmp4/5ioK/fInUKu6J8Jcm9YqEaAgQ9fVeAIufDA=
  - secure: tIrMxpM3nn3kqCoBozm3Xe6cgt4Dlu2Tdp6/2lsLdQsWQ/VfSd5fAijBGlwQ6W0OflkWb0rplh2H7JD1dGL7a9uPsU/9e31JnjkD7UqqtwSIN/BxXJ5EJ7cLnSQbQQUmh9QVbrDF4cc67itZoFRgH/agdr95hyNI7oXFPPOk49j1yLAIn44m8ReXT3z5HPd2ADzgBoHkVhOo6pC+ICZTXcgSKSPa9F8nmZRNaH1DY1V5SaUzmuMXRrwx8vsLOB4YWTE868ChTkAoOWAkMdw+7B/mbPoTe2rGyWnSCOlgts+I2zmh1H9RLPrjo7ZvYAI+fR9ETZnynQMq5MnNkWEf99MBwPmddSKFHruwMuAFNhbXVW2lYWSPtlIazaXUdnbzMamFN3JcPIchzIJG1MBhglrh7gjufW205Elm3oIjFeAbG53Dfv2efUM0PYYxPyc5bFD8xlVyBmM9yJ0EHZ/be4qFYhADVvTpXvp3Z2YYh5Vnlo1TLigMWltzZrrKG3aa8++HHVcgXVLy6/DYvcaZ3/+9xdPsCQDudpQkOTTXwEFIDOf161ndjm4m1UDoyu0rJdeailWxVYn+oeHnDPJbDZiQFXw3IhbxI05G+ZMyNSLaOoK0AoI9GzAK6nJZC8cBFCyqgrbBboJK3CKrzp3MiAulJLNxdPoTtVcQl5JNTlY=
  - secure: G/aMEDca/33i1aqpggRg0MB9peUkBwHIZZaiT9PqY12Mi1M6T3x5EG5WAYLc6KThlf6Av5TGdPg3kckyyr11EfpfsUXgiRCiGz9NCsgJhfGbSzdFXtyiTcoorboBEkAJ/2HQdbI82ihmLpfWrN5Rm1iFhRSa84rmLj2c6b17B0srJUh/lAz3SEaxsBSa9miLrJ30Pi28IW2pHuuML9mt2BWApU9+aFwi+35uDZjgcI0XQBaHRlYFzqmBag18DH3HrCMvoR0DpAXiBz03PFSHuWSt/Oam+NI+XwRz+sjDyzEAEGyJJYNf0lIeflbBMtTrwd57ZUGj1tQs0eQYdP57KZrsLKNzBjQn6S9iaXkvhL79HpsbDbAKalUqM/F8bhxAMEhloY95WayrKnG6G87BtZ99nwfSFdvJ8Oby6PYSCUap+7lHlTKiWGShTIqd5FUkyHX2liDnWul3VfK5FXgsDNl+h0kJm8SAsHRWPNXSPs9e7tqLpxkN0xKl2EvDUlccEX50nlOT7J7zjWaodvMhkoVzSddr/uf/ubz4rlDhjCD6GJEVXbilQuh07New/r9Q6D1CIRByznvdzQUb1HkvoYk4ljahJAnwVt5tYX9asOlWUIPfTQttE2JaLupZkdyT8Tqar4vmcoN1Gzre8F8juAzlBX7v5NwaQR3d7JirfTU=
addons:
  firefox: latest
  chrome: stable
language: java
cache:
  directories:
  - "$HOME/.gradle"
jdk:
- oraclejdk8
before_script:
- rm -rf target
script:
- if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./travis-build-pr.sh; fi
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./travis-build.sh; fi
